### ISSUE TITLE
Lab 11 complete!

### ISSUE THREAD

**Issue by estone65** [DataScience4Psych/lab-11-inference-smoking#5]
@smasongarrison

https://github.com/estone65/module12-lab11

I'm not sure that I approached all of the items quite the way you intended, and I definitely needed some help from chat on some things, but all told I found this to be the most interesting lab so far.  I hadn't spent much time with bootstrapping before, so some of that was new. I definitely see why you thought I should do this prior to simulations!

I'm pretty much done with R until I get back to Winston Salem, but I'll do the simulations lab then!

**Comment by smasongarrison** [comment]
:)
